In [1]:
import numpy as np

In [7]:
ar = np.array([0,1,2,3,4,5.2,6,7,8,9,'g'])
print(ar)

print(type(ar[2]))



['0' '1' '2' '3' '4' '5.2' '6' '7' '8' '9' 'g']
<class 'numpy.str_'>


In [9]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [11]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
2 * x
# 그냥 2배 가능

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
L = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(2 * L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [15]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
2 * a + b


array([12, 24, 36])

In [30]:
aa = np.array([1,2,3])
bb = np.array([[4,5,6],[7,8,9]])
2*aa+bb
print(aa.shape[0])
print(a.shape)
print(bb.shape)

3
(3,)
(2, 3)


In [16]:
a == 2

array([False,  True, False])

In [17]:
b > 10

array([False,  True,  True])

In [18]:
(a == 2) & (b > 10)

array([False,  True, False])

In [31]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])

In [32]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [59]:
print(d[1][2][1])
print(d[1,1,1:3])
print(type(d[1,1,1:3]))


print(d[0,1:3,1:3])
print(d[0,1:,1:-1])

# print(d[:,2,2])

20
[16 17]
<class 'numpy.ndarray'>
[[ 6  7]
 [10 11]]
[[ 6  7]
 [10 11]]
[11 21]


In [35]:
c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [46]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:

연습 문제 4.1.3¶
다음 행렬과 같은 배열이 있다.

이 배열에서 3의 배수를 찾아라.
이 배열에서 4로 나누면 1이 남는 수를 찾아라.
이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [88]:

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

a = x%3 ==0

b = x%4 ==1

c = a*b
print(x[c])


#x에 c를 연산
# 곱하면은 앤드연산
# 더하면은 or연산

[9]
